# Generated by Django 3.0.6 on 2020-06-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology')], default='unknown', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=40)),
                ('story', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('category', models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology')], default='unknown', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=40)),
                ('story', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlogd.VideoPost')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlogd.ImagePost')),
            ],
        ),
    ]
