# Generated by Django 3.0.6 on 2020-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology')], default='unknown', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=40)),
                ('story', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
