# Generated by Django 3.0.6 on 2020-06-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0002_youtubepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubePostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlogd.YoutubePost')),
            ],
        ),
    ]
