# Generated by Django 3.0.6 on 2020-06-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0003_youtubepostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='category',
            field=models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Matatu Culture', 'matatu culture'), ('Memes and Vines', 'memes and vines'), ('Music and Series Review', 'music and series review'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology'), ('Youths Corner', 'youths corner')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='category',
            field=models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Matatu Culture', 'matatu culture'), ('Memes and Vines', 'memes and vines'), ('Music and Series Review', 'music and series review'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology'), ('Youths Corner', 'youths corner')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='youtubepost',
            name='category',
            field=models.CharField(choices=[('Unknown', 'unknown'), ('Lifestyle', 'lifestyle'), ('Business', 'business'), ('Cars', 'cars'), ('Celebrity', 'celebrity'), ('History', 'history'), ('Matatu Culture', 'matatu culture'), ('Memes and Vines', 'memes and vines'), ('Music and Series Review', 'music and series review'), ('Politics', 'politics'), ('Sports', 'sports'), ('Technology', 'technology'), ('Youths Corner', 'youths corner')], default='unknown', max_length=100),
        ),
    ]
