# Generated by Django 3.0.6 on 2020-06-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0004_auto_20200610_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('newsletter', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='yes', max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='videopostcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='youtubepostcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='ImagePostComment',
        ),
        migrations.DeleteModel(
            name='VideoPostComment',
        ),
        migrations.DeleteModel(
            name='YoutubePostComment',
        ),
    ]
