# Generated by Django 3.0.6 on 2020-06-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0005_auto_20200615_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='newsletter',
            new_name='subscribe_newsletter',
        ),
    ]
