# Generated by Django 3.0.6 on 2020-06-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0006_auto_20200615_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subscribe_newsletter',
            new_name='receive_newsletter',
        ),
    ]
