# Generated by Django 3.0.6 on 2020-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0007_auto_20200615_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
