# Generated by Django 3.0.6 on 2020-06-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlogd', '0008_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='video',
            new_name='upload',
        ),
        migrations.AddField(
            model_name='videopost',
            name='upload_category',
            field=models.CharField(choices=[('Video', 'video'), ('Audio', 'audio')], default='unknown', max_length=50),
        ),
    ]
